<?php

namespace App\DataProviders;

abstract class CountryStateCityDataProvider
{
    public static function Countries()
    {
        return [
          
            ['id' => '18', 'name' => 'bangladesh']
            
        ];
    }

    public static function States()
    {
        return [
           
            ['id' => '337', 'country_id' => '18', 'name' => 'bagar hat'],
            ['id' => '338', 'country_id' => '18', 'name' => 'bandarban'],
            ['id' => '339', 'country_id' => '18', 'name' => 'barguna'],
            ['id' => '340', 'country_id' => '18', 'name' => 'barisal'],
            ['id' => '341', 'country_id' => '18', 'name' => 'bhola'],
            ['id' => '342', 'country_id' => '18', 'name' => 'bogora'],
            ['id' => '343', 'country_id' => '18', 'name' => 'brahman bariya'],
            ['id' => '344', 'country_id' => '18', 'name' => 'chandpur'],
            ['id' => '345', 'country_id' => '18', 'name' => 'chattagam'],
            ['id' => '346', 'country_id' => '18', 'name' => 'chittagong division'],
            ['id' => '347', 'country_id' => '18', 'name' => 'chuadanga'],
            ['id' => '348', 'country_id' => '18', 'name' => 'dhaka'],
            ['id' => '349', 'country_id' => '18', 'name' => 'dinajpur'],
            ['id' => '350', 'country_id' => '18', 'name' => 'faridpur'],
            ['id' => '351', 'country_id' => '18', 'name' => 'feni'],
            ['id' => '352', 'country_id' => '18', 'name' => 'gaybanda'],
            ['id' => '353', 'country_id' => '18', 'name' => 'gazipur'],
            ['id' => '354', 'country_id' => '18', 'name' => 'gopalganj'],
            ['id' => '355', 'country_id' => '18', 'name' => 'habiganj'],
            ['id' => '356', 'country_id' => '18', 'name' => 'jaipur hat'],
            ['id' => '357', 'country_id' => '18', 'name' => 'jamalpur'],
            ['id' => '358', 'country_id' => '18', 'name' => 'jessor'],
            ['id' => '359', 'country_id' => '18', 'name' => 'jhalakati'],
            ['id' => '360', 'country_id' => '18', 'name' => 'jhanaydah'],
            ['id' => '361', 'country_id' => '18', 'name' => 'khagrachhari'],
            ['id' => '362', 'country_id' => '18', 'name' => 'khulna'],
            ['id' => '363', 'country_id' => '18', 'name' => 'kishorganj'],
            ['id' => '364', 'country_id' => '18', 'name' => 'koks bazar'],
            ['id' => '365', 'country_id' => '18', 'name' => 'komilla'],
            ['id' => '366', 'country_id' => '18', 'name' => 'kurigram'],
            ['id' => '367', 'country_id' => '18', 'name' => 'kushtiya'],
            ['id' => '368', 'country_id' => '18', 'name' => 'lakshmipur'],
            ['id' => '369', 'country_id' => '18', 'name' => 'lalmanir hat'],
            ['id' => '370', 'country_id' => '18', 'name' => 'madaripur'],
            ['id' => '371', 'country_id' => '18', 'name' => 'magura'],
            ['id' => '372', 'country_id' => '18', 'name' => 'maimansingh'],
            ['id' => '373', 'country_id' => '18', 'name' => 'manikganj'],
            ['id' => '374', 'country_id' => '18', 'name' => 'maulvi bazar'],
            ['id' => '375', 'country_id' => '18', 'name' => 'meherpur'],
            ['id' => '376', 'country_id' => '18', 'name' => 'munshiganj'],
            ['id' => '377', 'country_id' => '18', 'name' => 'naral'],
            ['id' => '378', 'country_id' => '18', 'name' => 'narayanganj'],
            ['id' => '379', 'country_id' => '18', 'name' => 'narsingdi'],
            ['id' => '380', 'country_id' => '18', 'name' => 'nator'],
            ['id' => '381', 'country_id' => '18', 'name' => 'naugaon'],
            ['id' => '382', 'country_id' => '18', 'name' => 'nawabganj'],
            ['id' => '383', 'country_id' => '18', 'name' => 'netrakona'],
            ['id' => '384', 'country_id' => '18', 'name' => 'nilphamari'],
            ['id' => '385', 'country_id' => '18', 'name' => 'noakhali'],
            ['id' => '386', 'country_id' => '18', 'name' => 'pabna'],
            ['id' => '387', 'country_id' => '18', 'name' => 'panchagarh'],
            ['id' => '388', 'country_id' => '18', 'name' => 'patuakhali'],
            ['id' => '389', 'country_id' => '18', 'name' => 'pirojpur'],
            ['id' => '390', 'country_id' => '18', 'name' => 'rajbari'],
            ['id' => '391', 'country_id' => '18', 'name' => 'rajshahi'],
            ['id' => '392', 'country_id' => '18', 'name' => 'rangamati'],
            ['id' => '393', 'country_id' => '18', 'name' => 'rangpur'],
            ['id' => '394', 'country_id' => '18', 'name' => 'satkhira'],
            ['id' => '395', 'country_id' => '18', 'name' => 'shariatpur'],
            ['id' => '396', 'country_id' => '18', 'name' => 'sherpur'],
            ['id' => '397', 'country_id' => '18', 'name' => 'silhat'],
            ['id' => '398', 'country_id' => '18', 'name' => 'sirajganj'],
            ['id' => '399', 'country_id' => '18', 'name' => 'sunamganj'],
            ['id' => '400', 'country_id' => '18', 'name' => 'tangayal'],
            ['id' => '401', 'country_id' => '18', 'name' => 'thakurgaon'],
           
        ];
    }

    public static function Cities()
    {
        return [
            ['id' => '7264', 'state_id' => '338', 'name' => 'bandarban'],
            ['id' => '7265', 'state_id' => '339', 'name' => 'barguna'],
            ['id' => '7266', 'state_id' => '340', 'name' => 'barisal'],
            ['id' => '7267', 'state_id' => '340', 'name' => 'gaurnadi'],
            ['id' => '7268', 'state_id' => '340', 'name' => 'mehendiganj'],
            ['id' => '7269', 'state_id' => '340', 'name' => 'nalchiti'],
            ['id' => '7270', 'state_id' => '341', 'name' => 'bhola'],
            ['id' => '7271', 'state_id' => '341', 'name' => 'burhanuddin'],
            ['id' => '7272', 'state_id' => '341', 'name' => 'char fasson'],
            ['id' => '7273', 'state_id' => '341', 'name' => 'lalmohan'],
            ['id' => '7274', 'state_id' => '342', 'name' => 'adamighi'],
            ['id' => '7275', 'state_id' => '342', 'name' => 'bogora'],
            ['id' => '7276', 'state_id' => '342', 'name' => 'sherpur'],
            ['id' => '7277', 'state_id' => '344', 'name' => 'chandpur'],
            ['id' => '7278', 'state_id' => '344', 'name' => 'hajiganj'],
            ['id' => '7279', 'state_id' => '345', 'name' => 'boalkhali'],
            ['id' => '7280', 'state_id' => '345', 'name' => 'chattagam'],
            ['id' => '7281', 'state_id' => '345', 'name' => 'fatikchhari'],
            ['id' => '7282', 'state_id' => '345', 'name' => 'lohagara'],
            ['id' => '7283', 'state_id' => '345', 'name' => 'patiya'],
            ['id' => '7284', 'state_id' => '345', 'name' => 'rangunia'],
            ['id' => '7285', 'state_id' => '345', 'name' => 'raozan'],
            ['id' => '7286', 'state_id' => '345', 'name' => 'sandip'],
            ['id' => '7287', 'state_id' => '345', 'name' => 'satkaniya'],
            ['id' => '7288', 'state_id' => '347', 'name' => 'alamdanga'],
            ['id' => '7289', 'state_id' => '347', 'name' => 'chuadanga'],
            ['id' => '7290', 'state_id' => '347', 'name' => 'damurhuda'],
            ['id' => '7291', 'state_id' => '348', 'name' => 'dhaka'],
            ['id' => '7292', 'state_id' => '348', 'name' => 'dhamrai'],
            ['id' => '7293', 'state_id' => '348', 'name' => 'dohar'],
            ['id' => '7294', 'state_id' => '349', 'name' => 'bochanganj'],
            ['id' => '7295', 'state_id' => '349', 'name' => 'dinajpur'],
            ['id' => '7296', 'state_id' => '349', 'name' => 'fulbari'],
            ['id' => '7297', 'state_id' => '349', 'name' => 'parbatipur'],
            ['id' => '7298', 'state_id' => '350', 'name' => 'bhanga'],
            ['id' => '7299', 'state_id' => '350', 'name' => 'char bhadrasan'],
            ['id' => '7300', 'state_id' => '350', 'name' => 'faridpur'],
            ['id' => '7301', 'state_id' => '351', 'name' => 'chhagalnaiya'],
            ['id' => '7302', 'state_id' => '351', 'name' => 'feni'],
            ['id' => '7303', 'state_id' => '352', 'name' => 'gaybanda'],
            ['id' => '7304', 'state_id' => '353', 'name' => 'gazipur'],
            ['id' => '7305', 'state_id' => '353', 'name' => 'tungi'],
            ['id' => '7306', 'state_id' => '354', 'name' => 'gopalganj'],
            ['id' => '7307', 'state_id' => '354', 'name' => 'tungi para'],
            ['id' => '7308', 'state_id' => '355', 'name' => 'baniachang'],
            ['id' => '7309', 'state_id' => '355', 'name' => 'habiganj'],
            ['id' => '7310', 'state_id' => '357', 'name' => 'jamalpur'],
            ['id' => '7311', 'state_id' => '357', 'name' => 'sarishabari'],
            ['id' => '7312', 'state_id' => '358', 'name' => 'abhaynagar'],
            ['id' => '7313', 'state_id' => '358', 'name' => 'jessor'],
            ['id' => '7314', 'state_id' => '358', 'name' => 'jhikargachha'],
            ['id' => '7315', 'state_id' => '358', 'name' => 'keshabpur'],
            ['id' => '7316', 'state_id' => '359', 'name' => 'jhalakati'],
            ['id' => '7317', 'state_id' => '360', 'name' => 'jhanaydah'],
            ['id' => '7318', 'state_id' => '360', 'name' => 'kaliganj'],
            ['id' => '7319', 'state_id' => '360', 'name' => 'kotchandpur'],
            ['id' => '7320', 'state_id' => '360', 'name' => 'shailkupa'],
            ['id' => '7321', 'state_id' => '361', 'name' => 'khagrachari'],
            ['id' => '7322', 'state_id' => '361', 'name' => 'manikchhari'],
            ['id' => '7323', 'state_id' => '361', 'name' => 'ramgarh'],
            ['id' => '7324', 'state_id' => '362', 'name' => 'khulna'],
            ['id' => '7325', 'state_id' => '362', 'name' => 'phultala'],
            ['id' => '7326', 'state_id' => '363', 'name' => 'bajitpur'],
            ['id' => '7327', 'state_id' => '363', 'name' => 'bhairab bazar'],
            ['id' => '7328', 'state_id' => '363', 'name' => 'itna'],
            ['id' => '7329', 'state_id' => '363', 'name' => 'kishorganj'],
            ['id' => '7330', 'state_id' => '365', 'name' => 'komilla'],
            ['id' => '7331', 'state_id' => '365', 'name' => 'laksham'],
            ['id' => '7332', 'state_id' => '366', 'name' => 'chilmari'],
            ['id' => '7333', 'state_id' => '366', 'name' => 'kurigram'],
            ['id' => '7334', 'state_id' => '366', 'name' => 'nageshwari'],
            ['id' => '7335', 'state_id' => '366', 'name' => 'ulipur'],
            ['id' => '7336', 'state_id' => '367', 'name' => 'bheramara'],
            ['id' => '7337', 'state_id' => '367', 'name' => 'kushtiya'],
            ['id' => '7338', 'state_id' => '368', 'name' => 'lakshmipur'],
            ['id' => '7339', 'state_id' => '368', 'name' => 'ramganj'],
            ['id' => '7340', 'state_id' => '368', 'name' => 'ramgati'],
            ['id' => '7341', 'state_id' => '368', 'name' => 'raypur'],
            ['id' => '7342', 'state_id' => '370', 'name' => 'madaripur'],
            ['id' => '7343', 'state_id' => '371', 'name' => 'magura'],
            ['id' => '7344', 'state_id' => '372', 'name' => 'bhaluka'],
            ['id' => '7345', 'state_id' => '372', 'name' => 'fulbaria'],
            ['id' => '7346', 'state_id' => '372', 'name' => 'gafargaon'],
            ['id' => '7347', 'state_id' => '372', 'name' => 'ishwarganj'],
            ['id' => '7348', 'state_id' => '372', 'name' => 'maimansingh'],
            ['id' => '7349', 'state_id' => '372', 'name' => 'muktagachha'],
            ['id' => '7350', 'state_id' => '372', 'name' => 'trishal'],
            ['id' => '7351', 'state_id' => '373', 'name' => 'manikganj'],
            ['id' => '7352', 'state_id' => '375', 'name' => 'meherpur'],
            ['id' => '7353', 'state_id' => '376', 'name' => 'munshiganj'],
            ['id' => '7354', 'state_id' => '377', 'name' => 'kalia'],
            ['id' => '7355', 'state_id' => '377', 'name' => 'naral'],
            ['id' => '7356', 'state_id' => '378', 'name' => 'narayanganj'],
            ['id' => '7357', 'state_id' => '378', 'name' => 'rupganj'],
            ['id' => '7358', 'state_id' => '379', 'name' => 'narsingdi'],
            ['id' => '7359', 'state_id' => '379', 'name' => 'roypura'],
            ['id' => '7360', 'state_id' => '380', 'name' => 'gurudaspur'],
            ['id' => '7361', 'state_id' => '380', 'name' => 'nator'],
            ['id' => '7362', 'state_id' => '381', 'name' => 'naugaon'],
            ['id' => '7363', 'state_id' => '382', 'name' => 'gomastapur'],
            ['id' => '7364', 'state_id' => '382', 'name' => 'nawabganj'],
            ['id' => '7365', 'state_id' => '382', 'name' => 'shibganj'],
            ['id' => '7366', 'state_id' => '383', 'name' => 'netrakona'],
            ['id' => '7367', 'state_id' => '384', 'name' => 'domar'],
            ['id' => '7368', 'state_id' => '384', 'name' => 'nilphamari'],
            ['id' => '7369', 'state_id' => '384', 'name' => 'sa\'idpur'],
            ['id' => '7370', 'state_id' => '385', 'name' => 'begamganj'],
            ['id' => '7371', 'state_id' => '385', 'name' => 'noakhali'],
            ['id' => '7372', 'state_id' => '385', 'name' => 'senbagh'],
            ['id' => '7373', 'state_id' => '386', 'name' => 'bera'],
            ['id' => '7374', 'state_id' => '386', 'name' => 'bhangura'],
            ['id' => '7375', 'state_id' => '386', 'name' => 'ishurdi'],
            ['id' => '7376', 'state_id' => '386', 'name' => 'pabna'],
            ['id' => '7377', 'state_id' => '387', 'name' => 'panchagarh'],
            ['id' => '7378', 'state_id' => '388', 'name' => 'patuakhali'],
            ['id' => '7379', 'state_id' => '389', 'name' => 'bhandaria'],
            ['id' => '7380', 'state_id' => '389', 'name' => 'mathbaria'],
            ['id' => '7381', 'state_id' => '389', 'name' => 'nesarabad'],
            ['id' => '7382', 'state_id' => '389', 'name' => 'pirojpur'],
            ['id' => '7383', 'state_id' => '390', 'name' => 'pangsha'],
            ['id' => '7384', 'state_id' => '390', 'name' => 'rajbari'],
            ['id' => '7385', 'state_id' => '391', 'name' => 'rajshahi'],
            ['id' => '7386', 'state_id' => '392', 'name' => 'kaptai'],
            ['id' => '7387', 'state_id' => '392', 'name' => 'rangamati'],
            ['id' => '7388', 'state_id' => '393', 'name' => 'badarganj'],
            ['id' => '7389', 'state_id' => '393', 'name' => 'kaunia'],
            ['id' => '7390', 'state_id' => '393', 'name' => 'rangpur'],
            ['id' => '7391', 'state_id' => '394', 'name' => 'satkhira'],
            ['id' => '7392', 'state_id' => '395', 'name' => 'palang'],
            ['id' => '7393', 'state_id' => '396', 'name' => 'nalitabari'],
            ['id' => '7394', 'state_id' => '396', 'name' => 'sherpur'],
            ['id' => '7395', 'state_id' => '397', 'name' => 'silhat'],
            ['id' => '7396', 'state_id' => '398', 'name' => 'shahjadpur'],
            ['id' => '7397', 'state_id' => '398', 'name' => 'sirajganj'],
            ['id' => '7398', 'state_id' => '399', 'name' => 'chhatak'],
            ['id' => '7399', 'state_id' => '399', 'name' => 'sunamganj'],
            ['id' => '7400', 'state_id' => '400', 'name' => 'gopalpur'],
            ['id' => '7401', 'state_id' => '400', 'name' => 'mirzapur'],
            ['id' => '7402', 'state_id' => '400', 'name' => 'sakhipur'],
            ['id' => '7403', 'state_id' => '400', 'name' => 'tangayal'],
            ['id' => '7404', 'state_id' => '401', 'name' => 'pirganj'],
            ['id' => '7405', 'state_id' => '401', 'name' => 'thakurgaon'],
        ];
    }
}